//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SysPronatecModel", "FKEndereço187407", "Pessoa", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Pronatec.Entity.Pessoa), "Endereço", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Pronatec.Entity.Endereço), true)]

#endregion

namespace Pronatec.Entity
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SysPronatecEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SysPronatecEntities object using the connection string found in the 'SysPronatecEntities' section of the application configuration file.
        /// </summary>
        public SysPronatecEntities() : base("name=SysPronatecEntities", "SysPronatecEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SysPronatecEntities object.
        /// </summary>
        public SysPronatecEntities(string connectionString) : base(connectionString, "SysPronatecEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SysPronatecEntities object.
        /// </summary>
        public SysPronatecEntities(EntityConnection connection) : base(connection, "SysPronatecEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pessoa> Pessoa
        {
            get
            {
                if ((_Pessoa == null))
                {
                    _Pessoa = base.CreateObjectSet<Pessoa>("Pessoa");
                }
                return _Pessoa;
            }
        }
        private ObjectSet<Pessoa> _Pessoa;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Endereço> Endereço
        {
            get
            {
                if ((_Endereço == null))
                {
                    _Endereço = base.CreateObjectSet<Endereço>("Endereço");
                }
                return _Endereço;
            }
        }
        private ObjectSet<Endereço> _Endereço;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Curso> Curso
        {
            get
            {
                if ((_Curso == null))
                {
                    _Curso = base.CreateObjectSet<Curso>("Curso");
                }
                return _Curso;
            }
        }
        private ObjectSet<Curso> _Curso;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pessoa EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPessoa(Pessoa pessoa)
        {
            base.AddObject("Pessoa", pessoa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Endereço EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEndereço(Endereço endereço)
        {
            base.AddObject("Endereço", endereço);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Curso EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCurso(Curso curso)
        {
            base.AddObject("Curso", curso);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SysPronatecModel", Name="Curso")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Curso : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Curso object.
        /// </summary>
        /// <param name="idCurso">Initial value of the IdCurso property.</param>
        /// <param name="nomeCurso">Initial value of the NomeCurso property.</param>
        /// <param name="local">Initial value of the Local property.</param>
        public static Curso CreateCurso(global::System.Int16 idCurso, global::System.String nomeCurso, global::System.String local)
        {
            Curso curso = new Curso();
            curso.IdCurso = idCurso;
            curso.NomeCurso = nomeCurso;
            curso.Local = local;
            return curso;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 IdCurso
        {
            get
            {
                return _IdCurso;
            }
            set
            {
                if (_IdCurso != value)
                {
                    OnIdCursoChanging(value);
                    ReportPropertyChanging("IdCurso");
                    _IdCurso = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCurso");
                    OnIdCursoChanged();
                }
            }
        }
        private global::System.Int16 _IdCurso;
        partial void OnIdCursoChanging(global::System.Int16 value);
        partial void OnIdCursoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NomeCurso
        {
            get
            {
                return _NomeCurso;
            }
            set
            {
                OnNomeCursoChanging(value);
                ReportPropertyChanging("NomeCurso");
                _NomeCurso = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NomeCurso");
                OnNomeCursoChanged();
            }
        }
        private global::System.String _NomeCurso;
        partial void OnNomeCursoChanging(global::System.String value);
        partial void OnNomeCursoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Local
        {
            get
            {
                return _Local;
            }
            set
            {
                OnLocalChanging(value);
                ReportPropertyChanging("Local");
                _Local = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Local");
                OnLocalChanged();
            }
        }
        private global::System.String _Local;
        partial void OnLocalChanging(global::System.String value);
        partial void OnLocalChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SysPronatecModel", Name="Endereço")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Endereço : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Endereço object.
        /// </summary>
        /// <param name="iDEndereco">Initial value of the IDEndereco property.</param>
        /// <param name="rua">Initial value of the Rua property.</param>
        /// <param name="bairro">Initial value of the Bairro property.</param>
        /// <param name="numeroCasa">Initial value of the NumeroCasa property.</param>
        /// <param name="complemento">Initial value of the Complemento property.</param>
        /// <param name="idPessoa">Initial value of the IdPessoa property.</param>
        public static Endereço CreateEndereço(global::System.Int16 iDEndereco, global::System.String rua, global::System.String bairro, global::System.Int16 numeroCasa, global::System.String complemento, global::System.Int64 idPessoa)
        {
            Endereço endereço = new Endereço();
            endereço.IDEndereco = iDEndereco;
            endereço.Rua = rua;
            endereço.Bairro = bairro;
            endereço.NumeroCasa = numeroCasa;
            endereço.Complemento = complemento;
            endereço.IdPessoa = idPessoa;
            return endereço;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 IDEndereco
        {
            get
            {
                return _IDEndereco;
            }
            set
            {
                if (_IDEndereco != value)
                {
                    OnIDEnderecoChanging(value);
                    ReportPropertyChanging("IDEndereco");
                    _IDEndereco = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDEndereco");
                    OnIDEnderecoChanged();
                }
            }
        }
        private global::System.Int16 _IDEndereco;
        partial void OnIDEnderecoChanging(global::System.Int16 value);
        partial void OnIDEnderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Rua
        {
            get
            {
                return _Rua;
            }
            set
            {
                OnRuaChanging(value);
                ReportPropertyChanging("Rua");
                _Rua = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Rua");
                OnRuaChanged();
            }
        }
        private global::System.String _Rua;
        partial void OnRuaChanging(global::System.String value);
        partial void OnRuaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Bairro
        {
            get
            {
                return _Bairro;
            }
            set
            {
                OnBairroChanging(value);
                ReportPropertyChanging("Bairro");
                _Bairro = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Bairro");
                OnBairroChanged();
            }
        }
        private global::System.String _Bairro;
        partial void OnBairroChanging(global::System.String value);
        partial void OnBairroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 NumeroCasa
        {
            get
            {
                return _NumeroCasa;
            }
            set
            {
                OnNumeroCasaChanging(value);
                ReportPropertyChanging("NumeroCasa");
                _NumeroCasa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumeroCasa");
                OnNumeroCasaChanged();
            }
        }
        private global::System.Int16 _NumeroCasa;
        partial void OnNumeroCasaChanging(global::System.Int16 value);
        partial void OnNumeroCasaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Complemento
        {
            get
            {
                return _Complemento;
            }
            set
            {
                OnComplementoChanging(value);
                ReportPropertyChanging("Complemento");
                _Complemento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Complemento");
                OnComplementoChanged();
            }
        }
        private global::System.String _Complemento;
        partial void OnComplementoChanging(global::System.String value);
        partial void OnComplementoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IdPessoa
        {
            get
            {
                return _IdPessoa;
            }
            set
            {
                OnIdPessoaChanging(value);
                ReportPropertyChanging("IdPessoa");
                _IdPessoa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPessoa");
                OnIdPessoaChanged();
            }
        }
        private global::System.Int64 _IdPessoa;
        partial void OnIdPessoaChanging(global::System.Int64 value);
        partial void OnIdPessoaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SysPronatecModel", "FKEndereço187407", "Pessoa")]
        public Pessoa Pessoa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("SysPronatecModel.FKEndereço187407", "Pessoa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("SysPronatecModel.FKEndereço187407", "Pessoa").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pessoa> PessoaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pessoa>("SysPronatecModel.FKEndereço187407", "Pessoa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pessoa>("SysPronatecModel.FKEndereço187407", "Pessoa", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SysPronatecModel", Name="Pessoa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pessoa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pessoa object.
        /// </summary>
        /// <param name="iDPessoa">Initial value of the IDPessoa property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="cPF">Initial value of the CPF property.</param>
        /// <param name="dataNas">Initial value of the DataNas property.</param>
        /// <param name="nomedaMae">Initial value of the NomedaMae property.</param>
        /// <param name="cor">Initial value of the Cor property.</param>
        public static Pessoa CreatePessoa(global::System.Int64 iDPessoa, global::System.String nome, global::System.String cPF, global::System.DateTime dataNas, global::System.String nomedaMae, global::System.String cor)
        {
            Pessoa pessoa = new Pessoa();
            pessoa.IDPessoa = iDPessoa;
            pessoa.Nome = nome;
            pessoa.CPF = cPF;
            pessoa.DataNas = dataNas;
            pessoa.NomedaMae = nomedaMae;
            pessoa.Cor = cor;
            return pessoa;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IDPessoa
        {
            get
            {
                return _IDPessoa;
            }
            set
            {
                if (_IDPessoa != value)
                {
                    OnIDPessoaChanging(value);
                    ReportPropertyChanging("IDPessoa");
                    _IDPessoa = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDPessoa");
                    OnIDPessoaChanged();
                }
            }
        }
        private global::System.Int64 _IDPessoa;
        partial void OnIDPessoaChanging(global::System.Int64 value);
        partial void OnIDPessoaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CPF
        {
            get
            {
                return _CPF;
            }
            set
            {
                OnCPFChanging(value);
                ReportPropertyChanging("CPF");
                _CPF = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CPF");
                OnCPFChanged();
            }
        }
        private global::System.String _CPF;
        partial void OnCPFChanging(global::System.String value);
        partial void OnCPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DataNas
        {
            get
            {
                return _DataNas;
            }
            set
            {
                OnDataNasChanging(value);
                ReportPropertyChanging("DataNas");
                _DataNas = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataNas");
                OnDataNasChanged();
            }
        }
        private global::System.DateTime _DataNas;
        partial void OnDataNasChanging(global::System.DateTime value);
        partial void OnDataNasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NomedaMae
        {
            get
            {
                return _NomedaMae;
            }
            set
            {
                OnNomedaMaeChanging(value);
                ReportPropertyChanging("NomedaMae");
                _NomedaMae = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NomedaMae");
                OnNomedaMaeChanged();
            }
        }
        private global::System.String _NomedaMae;
        partial void OnNomedaMaeChanging(global::System.String value);
        partial void OnNomedaMaeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Cor
        {
            get
            {
                return _Cor;
            }
            set
            {
                OnCorChanging(value);
                ReportPropertyChanging("Cor");
                _Cor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Cor");
                OnCorChanged();
            }
        }
        private global::System.String _Cor;
        partial void OnCorChanging(global::System.String value);
        partial void OnCorChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SysPronatecModel", "FKEndereço187407", "Endereço")]
        public EntityCollection<Endereço> Endereço
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Endereço>("SysPronatecModel.FKEndereço187407", "Endereço");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Endereço>("SysPronatecModel.FKEndereço187407", "Endereço", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
